### PR TITLE
Add constraint Cabal <= 1.20.0.2

### PR DESCRIPTION
**Pull request by michalseweryn**
Solution (temporary?) to issue #20.

### CODE REVIEW

**Comment by feuerbach** [comment]
Merged and released. Note that I [no longer maintain](https://ro-che.info/articles/2014-11-01-rebalancing-open-source-portfolio) this library. Let me know if you'd like to take over.

**Comment by feuerbach** [comment]
@hesselink treat this as a bug fix. The new version has been released that fixes the bug. The way you ensure that you get the fixed version is by putting a lower bound on this library's version.

**Comment by hesselink** [comment]
Yeah, that's another option, although that one requires action from all the people that depend on this package instead of only this package's maintainer (although there is none, currently ;)).

**Comment by feuerbach** [comment]
Options №4: make cabal a bit more intelligent about these things. Like, if one version of a package has an upper bound, propagate it for all the previous versions of that package. I think it'll do what the user wants in 99% cases.

**Comment by hesselink** [comment]
Yes, that also seems like a good option, tool support. An option on hackage to mass update all older versions would also do the trick.

**Pull request merged**
